name: Chronus Quantum Continuous Integration - Intel Build

on: 
        push:
                branches: '**'

jobs: 
        build_intel:
                runs-on: self-hosted


                steps:
                        - name: Checkout Current CQ Branch
                          uses: actions/checkout@v3


                        - name: Test Intel Build
                          run: |
                               source /home/ci_software/intel-21.1.1.sh
                               mkdir build
                               cd build
                               cmake -DLibint2_ROOT=/sw/libint/2/7/0/beta.6/intel/21/1/1 -DCMAKE_CXX_FLAGS='-O3' -DCMAKE_C_FLAGS='-O3' -DCMAKE_Fortran_FLAGS='-O3'  ..
                               make -j4
                               ctest
                                                                 



                          

