name: Chronus Quantum Continuous Integration - Docker Build

on:
        push:
                branches: '**'

jobs:
        build_docker_image:
              runs-on: self-hosted
              steps:
                -
                  name: Checkout
                  uses: actions/checkout@v3
                -
                  name: Set up QEMU
                  uses: docker/setup-qemu-action@v1
                -
                  name: Set up Docker Buildx
                  uses: docker/setup-buildx-action@v1
                -
                  name: Login to DockerHub
                  uses: docker/login-action@v1
                  with:
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_PASSWORD }}
                -
                  name: Test Building Docker Image
                  run: |
                     export CQ_VERSION=$(grep "project(ChronusQ" -A 7 CMakeLists.txt | grep "VERSION" | sed 's/ \+VERSION //')
                     docker build -t uwligroup/chronusq:$CQ_VERSION .
                     docker push uwligroup/chronusq:$CQ_VERSION
                     docker tag uwligroup/chronusq:$CQ_VERSION uwligroup/chronusq:latest
                     docker push uwligroup/chronusq:latest
                -
                  name: after_script
                  run: docker logout
                                

