name: Chronus Quantum Continuous Integration - GCC  Build

on: 
        push:
                branches: '**'

jobs: 
        build_gcc:
                runs-on: self-hosted


                steps:
                        - name: Checkout Current CQ Branch
                          uses: actions/checkout@v3


                        - name: Test GCC Build
                          run: |
                               ls -l
                                

