name: Chronus Quantum Continuous Integration - MPI GCC Build

on: 
        push:
                branches: [master]

jobs: 
        build_mpi_gcc:
                runs-on: self-hosted


                steps:
                        - name: Checkout Current CQ Branch
                          uses: actions/checkout@v3


                        - name: Test MPI GCC Build
                          run: |
                               source /home/ci_software/gcc-8.2.0_mpich-3.2.1.sh
                               mkdir build
                               cd build
                               cmake -DLibint2_ROOT=/sw/libint/2/7/0/beta.6/gcc/8/2/0 -DCMAKE_CXX_FLAGS='-O3' -DCMAKE_C_FLAGS='-O3' -DCMAKE_Fortran_FLAGS='-O3' -DCQ_ENABLE_MPI=ON  -DCQ_SCALAPACK_LIBRARIES="$SCALAPACK_LIBRARY_DIR/libscalapack.a" -DCMAKE_C_COMPILER=mpicc -DCMAKE_CXX_COMPILER=mpicxx -DCMAKE_BUILD_TYPE=Release ..
                               make -j4
                               ctest
                                                                 



                          

