name: Chronus Quantum Continuous Integration - Docker Build

on:
        push:
                branches: '**'

jobs:
        build_docker_image:
                runs-on: self-hosted

                steps:
                        - name: Building Docker Image
                          uses: actions/checkout@v3

                        - name: Test Building Docker Image
                          run:  |
                                echo $DOCKERHUB_USERNAME
                                echo $DOCKERHUB_PASSWORD
                                export CQ_VERSION=$(grep "project(ChronusQ" -A 7 CMakeLists.txt | grep "VERSION" | sed 's/ \+VERSION //')
                                docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
                                docker build -t uwligroup/chronusq:$CQ_VERSION .
                                docker push uwligroup/chronusq:$CQ_VERSION
                                docker tag uwligroup/chronusq:$CQ_VERSION uwligroup/chronusq:latest
                                docker push uwligroup/chronusq:latest
                                docker logout
                                

                               
