stages:
    - build

build_docker_images:
    stage: build
    only:
        - master
        - docker 
    before_script:
        - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
    script:
        - export CQ_VERSION=$(grep "project(ChronusQ" -A 7 CMakeLists.txt | grep "VERSION" | sed 's/ \+VERSION //')
        - docker build -t uwligroup/chronusq:$CQ_VERSION .
        - docker push uwligroup/chronusq:$CQ_VERSION
        - docker tag uwligroup/chronusq:$CQ_VERSION uwligroup/chronusq:latest
        - docker push uwligroup/chronusq:latest
    after_script:
        - docker logout

build_intel:
    stage: build
    artifacts:
        when: always
        paths:
            - build/Testing/Temporary/LastTest.log
        name: "$CI_JOB_ID-$CI_JOB_NAME"
    script:
        - source /home/ci_software/intel-21.1.1.sh
        - mkdir build
        - cd build
        - cmake -DLibint2_ROOT=/sw/libint/2/7/0/beta.6/intel/21/1/1 -DCMAKE_CXX_FLAGS='-O3' -DCMAKE_C_FLAGS='-O3' -DCMAKE_Fortran_FLAGS='-O3'  ..
        - make -j4
        - ctest

build_gcc:
    stage: build
    artifacts:
        when: always
        paths:
            - build/Testing/Temporary/LastTest.log
        name: "$CI_JOB_ID-$CI_JOB_NAME"
    script:
        - source /home/ci_software/gcc-10.2.0.sh
        - mkdir build
        - cd build
        - cmake -DLibint2_ROOT=/sw/libint/2/7/0/beta.6/gcc/10/2/0 -DCMAKE_CXX_FLAGS='-O3' -DCMAKE_C_FLAGS='-O3' -DCMAKE_Fortran_FLAGS='-O3' ..
        - make -j4
        - ctest

build_mpi_gcc:
    stage: build
    artifacts:
        when: always
        paths:
            - build/Testing/Temporary/LastTest.log
        name: "$CI_JOB_ID-$CI_JOB_NAME"
    script:
        - source /home/ci_software/gcc-8.2.0_mpich-3.2.1.sh
        - mkdir build
        - cd build
        - cmake -DLibint2_ROOT=/sw/libint/2/7/0/beta.6/gcc/8/2/0 -DCMAKE_CXX_FLAGS='-O3' -DCMAKE_C_FLAGS='-O3' -DCMAKE_Fortran_FLAGS='-O3' -DCQ_ENABLE_MPI=ON  -DCQ_SCALAPACK_LIBRARIES="$SCALAPACK_LIBRARY_DIR/libscalapack.a" -DCMAKE_C_COMPILER=mpicc -DCMAKE_CXX_COMPILER=mpicxx -DCMAKE_BUILD_TYPE=Release ..
        - make -j4
        - make test






